#include <ttak/mols_control.h>

#include <limits.h>

#define TTAK_MOLS_SYMBOL_BITS        (TTAK_MOLS_COORD_SHIFT)

#if USE_NONLINEAR

#if TTAK_MOLS_LUT_BITS < TTAK_MOLS_SYMBOL_BITS
#error "LUT resolution must be greater than or equal to symbol resolution."
#endif

#define TTAK_MOLS_LUT_SCALE          (65535U)
#define TTAK_MOLS_LUT_SCALE_SHIFT    (16U)
#define TTAK_MOLS_LUT_DEN_BASE       (255U)

#if TTAK_MOLS_LUT_BITS == TTAK_MOLS_SYMBOL_BITS
#define TTAK_MOLS_LUT_LOW_MASK       (0U)
#define TTAK_MOLS_LUT_SHIFT          (0U)
#else
#define TTAK_MOLS_LUT_SHIFT          (TTAK_MOLS_LUT_BITS - TTAK_MOLS_SYMBOL_BITS)
#define TTAK_MOLS_LUT_LOW_MASK       ((1U << TTAK_MOLS_LUT_SHIFT) - 1U)
#endif

/* Integer-only f(x) = 1/(1 + x) approximations stored as Q0.16 values. */
#define TTAK_INV_ENTRY(sample_) \
    ((uint16_t)((((uint32_t)TTAK_MOLS_LUT_SCALE * (uint32_t)TTAK_MOLS_LUT_DEN_BASE) + \
    (((uint32_t)TTAK_MOLS_LUT_DEN_BASE + (uint32_t)(sample_)) / 2U)) / \
    ((uint32_t)TTAK_MOLS_LUT_DEN_BASE + (uint32_t)(sample_))))

static const uint16_t ttak_inverse_map_lut[TTAK_MOLS_LUT_SIZE] = {
    TTAK_INV_ENTRY(0U), TTAK_INV_ENTRY(1U), TTAK_INV_ENTRY(2U), TTAK_INV_ENTRY(3U), TTAK_INV_ENTRY(4U), TTAK_INV_ENTRY(5U), TTAK_INV_ENTRY(6U), TTAK_INV_ENTRY(7U),
    TTAK_INV_ENTRY(8U), TTAK_INV_ENTRY(9U), TTAK_INV_ENTRY(10U), TTAK_INV_ENTRY(11U), TTAK_INV_ENTRY(12U), TTAK_INV_ENTRY(13U), TTAK_INV_ENTRY(14U), TTAK_INV_ENTRY(15U),
    TTAK_INV_ENTRY(16U), TTAK_INV_ENTRY(17U), TTAK_INV_ENTRY(18U), TTAK_INV_ENTRY(19U), TTAK_INV_ENTRY(20U), TTAK_INV_ENTRY(21U), TTAK_INV_ENTRY(22U), TTAK_INV_ENTRY(23U),
    TTAK_INV_ENTRY(24U), TTAK_INV_ENTRY(25U), TTAK_INV_ENTRY(26U), TTAK_INV_ENTRY(27U), TTAK_INV_ENTRY(28U), TTAK_INV_ENTRY(29U), TTAK_INV_ENTRY(30U), TTAK_INV_ENTRY(31U),
    TTAK_INV_ENTRY(32U), TTAK_INV_ENTRY(33U), TTAK_INV_ENTRY(34U), TTAK_INV_ENTRY(35U), TTAK_INV_ENTRY(36U), TTAK_INV_ENTRY(37U), TTAK_INV_ENTRY(38U), TTAK_INV_ENTRY(39U),
    TTAK_INV_ENTRY(40U), TTAK_INV_ENTRY(41U), TTAK_INV_ENTRY(42U), TTAK_INV_ENTRY(43U), TTAK_INV_ENTRY(44U), TTAK_INV_ENTRY(45U), TTAK_INV_ENTRY(46U), TTAK_INV_ENTRY(47U),
    TTAK_INV_ENTRY(48U), TTAK_INV_ENTRY(49U), TTAK_INV_ENTRY(50U), TTAK_INV_ENTRY(51U), TTAK_INV_ENTRY(52U), TTAK_INV_ENTRY(53U), TTAK_INV_ENTRY(54U), TTAK_INV_ENTRY(55U),
    TTAK_INV_ENTRY(56U), TTAK_INV_ENTRY(57U), TTAK_INV_ENTRY(58U), TTAK_INV_ENTRY(59U), TTAK_INV_ENTRY(60U), TTAK_INV_ENTRY(61U), TTAK_INV_ENTRY(62U), TTAK_INV_ENTRY(63U),
    TTAK_INV_ENTRY(64U), TTAK_INV_ENTRY(65U), TTAK_INV_ENTRY(66U), TTAK_INV_ENTRY(67U), TTAK_INV_ENTRY(68U), TTAK_INV_ENTRY(69U), TTAK_INV_ENTRY(70U), TTAK_INV_ENTRY(71U),
    TTAK_INV_ENTRY(72U), TTAK_INV_ENTRY(73U), TTAK_INV_ENTRY(74U), TTAK_INV_ENTRY(75U), TTAK_INV_ENTRY(76U), TTAK_INV_ENTRY(77U), TTAK_INV_ENTRY(78U), TTAK_INV_ENTRY(79U),
    TTAK_INV_ENTRY(80U), TTAK_INV_ENTRY(81U), TTAK_INV_ENTRY(82U), TTAK_INV_ENTRY(83U), TTAK_INV_ENTRY(84U), TTAK_INV_ENTRY(85U), TTAK_INV_ENTRY(86U), TTAK_INV_ENTRY(87U),
    TTAK_INV_ENTRY(88U), TTAK_INV_ENTRY(89U), TTAK_INV_ENTRY(90U), TTAK_INV_ENTRY(91U), TTAK_INV_ENTRY(92U), TTAK_INV_ENTRY(93U), TTAK_INV_ENTRY(94U), TTAK_INV_ENTRY(95U),
    TTAK_INV_ENTRY(96U), TTAK_INV_ENTRY(97U), TTAK_INV_ENTRY(98U), TTAK_INV_ENTRY(99U), TTAK_INV_ENTRY(100U), TTAK_INV_ENTRY(101U), TTAK_INV_ENTRY(102U), TTAK_INV_ENTRY(103U),
    TTAK_INV_ENTRY(104U), TTAK_INV_ENTRY(105U), TTAK_INV_ENTRY(106U), TTAK_INV_ENTRY(107U), TTAK_INV_ENTRY(108U), TTAK_INV_ENTRY(109U), TTAK_INV_ENTRY(110U), TTAK_INV_ENTRY(111U),
    TTAK_INV_ENTRY(112U), TTAK_INV_ENTRY(113U), TTAK_INV_ENTRY(114U), TTAK_INV_ENTRY(115U), TTAK_INV_ENTRY(116U), TTAK_INV_ENTRY(117U), TTAK_INV_ENTRY(118U), TTAK_INV_ENTRY(119U),
    TTAK_INV_ENTRY(120U), TTAK_INV_ENTRY(121U), TTAK_INV_ENTRY(122U), TTAK_INV_ENTRY(123U), TTAK_INV_ENTRY(124U), TTAK_INV_ENTRY(125U), TTAK_INV_ENTRY(126U), TTAK_INV_ENTRY(127U),
    TTAK_INV_ENTRY(128U), TTAK_INV_ENTRY(129U), TTAK_INV_ENTRY(130U), TTAK_INV_ENTRY(131U), TTAK_INV_ENTRY(132U), TTAK_INV_ENTRY(133U), TTAK_INV_ENTRY(134U), TTAK_INV_ENTRY(135U),
    TTAK_INV_ENTRY(136U), TTAK_INV_ENTRY(137U), TTAK_INV_ENTRY(138U), TTAK_INV_ENTRY(139U), TTAK_INV_ENTRY(140U), TTAK_INV_ENTRY(141U), TTAK_INV_ENTRY(142U), TTAK_INV_ENTRY(143U),
    TTAK_INV_ENTRY(144U), TTAK_INV_ENTRY(145U), TTAK_INV_ENTRY(146U), TTAK_INV_ENTRY(147U), TTAK_INV_ENTRY(148U), TTAK_INV_ENTRY(149U), TTAK_INV_ENTRY(150U), TTAK_INV_ENTRY(151U),
    TTAK_INV_ENTRY(152U), TTAK_INV_ENTRY(153U), TTAK_INV_ENTRY(154U), TTAK_INV_ENTRY(155U), TTAK_INV_ENTRY(156U), TTAK_INV_ENTRY(157U), TTAK_INV_ENTRY(158U), TTAK_INV_ENTRY(159U),
    TTAK_INV_ENTRY(160U), TTAK_INV_ENTRY(161U), TTAK_INV_ENTRY(162U), TTAK_INV_ENTRY(163U), TTAK_INV_ENTRY(164U), TTAK_INV_ENTRY(165U), TTAK_INV_ENTRY(166U), TTAK_INV_ENTRY(167U),
    TTAK_INV_ENTRY(168U), TTAK_INV_ENTRY(169U), TTAK_INV_ENTRY(170U), TTAK_INV_ENTRY(171U), TTAK_INV_ENTRY(172U), TTAK_INV_ENTRY(173U), TTAK_INV_ENTRY(174U), TTAK_INV_ENTRY(175U),
    TTAK_INV_ENTRY(176U), TTAK_INV_ENTRY(177U), TTAK_INV_ENTRY(178U), TTAK_INV_ENTRY(179U), TTAK_INV_ENTRY(180U), TTAK_INV_ENTRY(181U), TTAK_INV_ENTRY(182U), TTAK_INV_ENTRY(183U),
    TTAK_INV_ENTRY(184U), TTAK_INV_ENTRY(185U), TTAK_INV_ENTRY(186U), TTAK_INV_ENTRY(187U), TTAK_INV_ENTRY(188U), TTAK_INV_ENTRY(189U), TTAK_INV_ENTRY(190U), TTAK_INV_ENTRY(191U),
    TTAK_INV_ENTRY(192U), TTAK_INV_ENTRY(193U), TTAK_INV_ENTRY(194U), TTAK_INV_ENTRY(195U), TTAK_INV_ENTRY(196U), TTAK_INV_ENTRY(197U), TTAK_INV_ENTRY(198U), TTAK_INV_ENTRY(199U),
    TTAK_INV_ENTRY(200U), TTAK_INV_ENTRY(201U), TTAK_INV_ENTRY(202U), TTAK_INV_ENTRY(203U), TTAK_INV_ENTRY(204U), TTAK_INV_ENTRY(205U), TTAK_INV_ENTRY(206U), TTAK_INV_ENTRY(207U),
    TTAK_INV_ENTRY(208U), TTAK_INV_ENTRY(209U), TTAK_INV_ENTRY(210U), TTAK_INV_ENTRY(211U), TTAK_INV_ENTRY(212U), TTAK_INV_ENTRY(213U), TTAK_INV_ENTRY(214U), TTAK_INV_ENTRY(215U),
    TTAK_INV_ENTRY(216U), TTAK_INV_ENTRY(217U), TTAK_INV_ENTRY(218U), TTAK_INV_ENTRY(219U), TTAK_INV_ENTRY(220U), TTAK_INV_ENTRY(221U), TTAK_INV_ENTRY(222U), TTAK_INV_ENTRY(223U),
    TTAK_INV_ENTRY(224U), TTAK_INV_ENTRY(225U), TTAK_INV_ENTRY(226U), TTAK_INV_ENTRY(227U), TTAK_INV_ENTRY(228U), TTAK_INV_ENTRY(229U), TTAK_INV_ENTRY(230U), TTAK_INV_ENTRY(231U),
    TTAK_INV_ENTRY(232U), TTAK_INV_ENTRY(233U), TTAK_INV_ENTRY(234U), TTAK_INV_ENTRY(235U), TTAK_INV_ENTRY(236U), TTAK_INV_ENTRY(237U), TTAK_INV_ENTRY(238U), TTAK_INV_ENTRY(239U),
    TTAK_INV_ENTRY(240U), TTAK_INV_ENTRY(241U), TTAK_INV_ENTRY(242U), TTAK_INV_ENTRY(243U), TTAK_INV_ENTRY(244U), TTAK_INV_ENTRY(245U), TTAK_INV_ENTRY(246U), TTAK_INV_ENTRY(247U),
    TTAK_INV_ENTRY(248U), TTAK_INV_ENTRY(249U), TTAK_INV_ENTRY(250U), TTAK_INV_ENTRY(251U), TTAK_INV_ENTRY(252U), TTAK_INV_ENTRY(253U), TTAK_INV_ENTRY(254U), TTAK_INV_ENTRY(255U)
};

#undef TTAK_INV_ENTRY

#endif /* USE_NONLINEAR */

static inline uint32_t ttak_mols_symbol(uint16_t node_id)
{
    const uint32_t row = ((uint32_t)node_id >> TTAK_MOLS_COORD_SHIFT) & TTAK_MOLS_SYMBOL_MASK;
    const uint32_t col = (uint32_t)node_id & TTAK_MOLS_SYMBOL_MASK;
    return (row + col) & TTAK_MOLS_SYMBOL_MASK;
}

uint32_t ttak_apply_mols_control(uint16_t node_id, uint32_t current_load)
{
#if USE_NONLINEAR
    const uint32_t symbol = ttak_mols_symbol(node_id);
    uint32_t idx = (symbol << TTAK_MOLS_LUT_SHIFT);
#if TTAK_MOLS_LUT_SHIFT > 0U
    idx |= ((uint32_t)node_id & TTAK_MOLS_LUT_LOW_MASK);
#endif
    const uint16_t inverse = ttak_inverse_map_lut[idx];
    uint64_t dampened = ((uint64_t)current_load * (uint64_t)inverse) >> TTAK_MOLS_LUT_SCALE_SHIFT;
    if (dampened > (uint64_t)UINT32_MAX) {
        dampened = (uint64_t)UINT32_MAX;
    }
    return (uint32_t)dampened;
#else
    (void)node_id;
    return current_load;
#endif
}
