var searchData=
[
  ['access_5febr_20protected_20false_0',['&lt;span class=&quot;tt&quot;&gt;access_ebr(..., protected=false)&lt;/span&gt;',['..//home/yjlee/libttak/tutorials/38-ebr-shared/README.md#autotoc_md135',1,'']]],
  ['access_5febr_20protected_20true_1',['&lt;span class=&quot;tt&quot;&gt;access_ebr(..., protected=true)&lt;/span&gt;',['..//home/yjlee/libttak/tutorials/38-ebr-shared/README.md#autotoc_md134',1,'']]],
  ['adding_20new_20blueprints_2',['Adding New Blueprints',['..//home/yjlee/libttak/blueprints/README.md#autotoc_md15',1,'']]],
  ['aggregator_3',['Tutorial 19 – Stats Aggregator',['..//home/yjlee/libttak/tutorials/19-stats-aggregator/README.md#autotoc_md84',1,'']]],
  ['ai_20assisted_20development_4',['Practical Utility for AI-Assisted Development',['../index.html#autotoc_md33',1,'']]],
  ['aliquot_20integration_5',['Tutorial 32 – Aliquot Integration',['..//home/yjlee/libttak/tutorials/32-aliquot-integration/README.md#autotoc_md111',1,'']]],
  ['allocator_6',['Tutorial 05 – Pool Allocator',['..//home/yjlee/libttak/tutorials/05-pool-allocator/README.md#autotoc_md56',1,'']]],
  ['analysis_20tools_7',['Analysis Tools',['..//home/yjlee/libttak/bench/README.md#autotoc_md5',1,'']]],
  ['and_20arithmetic_8',['02 - Variables and Arithmetic',['..//home/yjlee/libttak/tutorials/43-bigscript/02-variables-arithmetic/README.md#autotoc_md162',1,'']]],
  ['and_20c_9',['Comparison: LibTTAK, Rust, and C++',['../index.html#autotoc_md37',1,'']]],
  ['and_20complex_20numbers_10',['05 - Real and Complex Numbers',['..//home/yjlee/libttak/tutorials/43-bigscript/05-complex-math/README.md#autotoc_md174',1,'']]],
  ['and_20construction_11',['Type Conversion and Construction',['..//home/yjlee/libttak/tutorials/43-bigscript/05-complex-math/README.md#autotoc_md175',1,'']]],
  ['and_20epochgc_20integration_12',['EBR and EpochGC Integration',['..//home/yjlee/libttak/tutorials/38-ebr-shared/README.md#autotoc_md137',1,'']]],
  ['and_20math_20tuning_13',['TCC-Oriented Build and Math Tuning',['../md_docs_2TCC__OPTIMIZATION.html',1,'']]],
  ['and_20running_14',['Building and Running',['..//home/yjlee/libttak/tutorials/38-ebr-shared/README.md#autotoc_md138',1,'']]],
  ['and_20sn_15',['Input Arguments: &lt;span class=&quot;tt&quot;&gt;seed&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sn&lt;/span&gt;',['..//home/yjlee/libttak/tutorials/43-bigscript/04-builtins/README.md#autotoc_md172',1,'']]],
  ['application_20layer_16',['Stage 8 – Application Layer',['../md_tutorials_2CLONE__PATH.html#autotoc_md191',1,'']]],
  ['applying_20the_20tricks_20elsewhere_17',['Applying the Tricks Elsewhere',['../md_docs_2TCC__OPTIMIZATION.html#autotoc_md21',1,'']]],
  ['architectural_20map_18',['Integrated Architectural Map',['../index.html#autotoc_md30',1,'']]],
  ['architectural_20philosophy_19',['Architectural Philosophy',['..//home/yjlee/libttak/bench/README.md#autotoc_md4',1,'']]],
  ['arena_20families_20signal_20guards_20',['Stage 10 – Arena Families &amp;amp; Signal Guards',['../md_tutorials_2CLONE__PATH.html#autotoc_md193',1,'']]],
  ['arena_20memory_20orchestration_21',['Lesson 40: Arena Memory Orchestration',['..//home/yjlee/libttak/tutorials/40-arena-memory/README.md#autotoc_md145',1,'']]],
  ['arguments_3a_20seed_20and_20sn_22',['Input Arguments: &lt;span class=&quot;tt&quot;&gt;seed&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sn&lt;/span&gt;',['..//home/yjlee/libttak/tutorials/43-bigscript/04-builtins/README.md#autotoc_md172',1,'']]],
  ['arithmetic_23',['02 - Variables and Arithmetic',['..//home/yjlee/libttak/tutorials/43-bigscript/02-variables-arithmetic/README.md#autotoc_md162',1,'']]],
  ['arithmetic_20operators_24',['Arithmetic Operators',['..//home/yjlee/libttak/tutorials/43-bigscript/02-variables-arithmetic/README.md#autotoc_md164',1,'']]],
  ['as_20data_25',['Deterministic Lifetime-as-Data',['../index.html#autotoc_md34',1,'']]],
  ['assembly_20strategy_26',['Portable Assembly Strategy',['../md_docs_2TCC__OPTIMIZATION.html#autotoc_md19',1,'']]],
  ['assisted_20development_27',['Practical Utility for AI-Assisted Development',['../index.html#autotoc_md33',1,'']]],
  ['ast_28',['Stage 7 – Trees + AST',['../md_tutorials_2CLONE__PATH.html#autotoc_md190',1,'']]],
  ['ast_20walking_29',['Tutorial 29 – AST Walking',['..//home/yjlee/libttak/tutorials/29-ast-walking/README.md#autotoc_md105',1,'']]],
  ['async_30',['Stage 3 – Thread Pool &amp;amp; Async',['../md_tutorials_2CLONE__PATH.html#autotoc_md186',1,'']]],
  ['async_20primitives_31',['Tutorial 15 – Async Primitives',['..//home/yjlee/libttak/tutorials/15-async-primitives/README.md#autotoc_md76',1,'']]],
  ['async_20scheduler_32',['Tutorial 16 – Async Scheduler',['..//home/yjlee/libttak/tutorials/16-async-scheduler/README.md#autotoc_md78',1,'']]],
  ['atomics_33',['Tutorial 11 – Portable Atomics',['..//home/yjlee/libttak/tutorials/11-portable-atomics/README.md#autotoc_md68',1,'']]]
];
